---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data
  namespace: h5ai
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  storageClassName: ""
  volumeName: nfs-files

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-files
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.20
    path: "/mnt/raidpool/files"
  mountOptions:
    - nfsvers=4.2
    - ro
  