apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Default project for all ArgoCD managed Applications
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/thomasbuchinger/prod-gitops'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - server: https://kubernetes.default.svc
