
apiVersion: batch/v1
kind: CronJob
metadata:
  name: workhours-reminder
spec:
  # ┌───────────── minute (0 - 59)
  # │ ┌───────────── hour (0 - 23)
  # │ │ ┌───────────── day of the month (1 - 31)
  # │ │ │ ┌───────────── month (1 - 12)
  # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
  # │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
  schedule: "0 18 * * 1-5"
  timeZone: Europe/Vienna
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: workhours-reminder
            image: alpine/curl:latest
            imagePullPolicy: IfNotPresent
            resources: {}
            env:
            - name: USER
              value: prodcluster
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: ntfy-creds-k8s
                  key: PROD_CLUSTER_PASSWORD
            command:
            - /bin/sh
            - -c
            - >-
              curl http://ntfy.ntfy.svc:8080/work_reminders -H "Title: Workday $(date '+%d.%m')" -d "How long did you work today?" -H "Tags: clock8" -H "Click: https://push.cloud.buc.sh/work_reminders"  -u $USER:$PASS
          restartPolicy: OnFailure

