---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
data:
  server.yml: |
    # Template: https://github.com/binwiederhier/ntfy/blob/main/server/server.yml
    base-url: http://push.10.0.0.21.nip.io
    listen-http: ":8080"
    behind-proxy: true
    # Set the Cache-Duration to 60 Days
    cache-duration: 1400h
    cache-file: /var/cache/ntfy/cache.db
    attachment-cache-dir: /var/cache/ntfy/attachments
    metrics-listen-http: ":8081"
    auth-file: /var/lib/ntfy/auth.db
    auth-default-access: deny-all
    enable-signup: false
    
    # Default that might be needed in the future
    # base-url: https://push.cloud.buc.sh
    # attachment-expiry-duration: 3h
    # attachment-total-size-limit: 5G
    # message-size-limit: # 4k
    # message-delay-limit: 
    # global-topic-limit: 15000
    # visitor-subscription-limit: 30
    # visitor-request-limit-burst: 60
    # visitor-request-limit-replenish: 5s
    # visitor-request-limit-exempt-hosts: "ip1,ip2,ip3"
    # visitor-message-daily-limit: 30
    # log-level: info
    # log-format: json
  initScript.sh: |
    SERVER="http://localhost:8080"
    curl $SERVER/v1/health || exit 1
    NTFY_PASSWORD=changeme ntfy user add --ignore-exists --role=admin buc
    NTFY_PASSWORD=changeme ntfy user add --ignore-exists api
    NTFY_PASSWORD=changeme ntfy user add --ignore-exists homelab
    NTFY_PASSWORD=changeme ntfy user add --ignore-exists webhook
    NTFY_PASSWORD=changeme ntfy user add --ignore-exists curl
    ntfy access buc      $SERVER/* rw

    ntfy access api      $SERVER/work-* rw
    ntfy access homelab  $SERVER/work-* write
    ntfy access everyone $SERVER/work-* read
    
    ntfy access api      $SERVER/homelab-* rw
    ntfy access homelab  $SERVER/homelab-* rw

    ntfy access api      $SERVER/buc-* rw
    
    ntfy access everyone $SERVER/open-readwrite-A4bPDqUr25mQzins rw
    ntfy access everyone $SERVER/open-write-cqgwAWUSsxMqo3pl write
    ntfy access everyone $SERVER/open-read-22LPVPsTxS6lUJOK read
    echo "Done configuring ntfy server"

# NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
# NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
# NTFY_AUTH_DEFAULT_ACCESS: deny-all
# NTFY_BEHIND_PROXY: true
# NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
# NTFY_ENABLE_LOGIN: true


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
spec:
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      containers:
      - name: ntfy
        image: binwiederhier/ntfy
        args: ["serve"]
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: metrics
        startupProbe:
          exec:
            command:
            - "sh /etc/ntfy/initScript.sh"
        livenessProbe:
          httpGet:
            port: 8080
            path: /v1/health
        readinessProbe:
          httpGet:
            port: 8080
            path: /v1/health
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: config
          mountPath: "/etc/ntfy"
          readOnly: true
        - name: cache
          mountPath: "/var/cache/ntfy"
        - name: data
          mountPath: "/var/lib/ntfy"
      volumes:
        - name: config
          configMap:
            name: ntfy
        - name: cache
          persistentVolumeClaim:
            claimName: ntfy-cache
        - name: data
          emptyDir: {}
---
# Basic service for port 80
apiVersion: v1
kind: Service
metadata:
  name: ntfy
spec:
  selector:
    app: ntfy
  ports:
  - name: http
    port: 8080
    targetPort: 8080


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy
spec:
  rules:
  - host: push.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ntfy
            port:
              name: http
  - host: push.10.0.0.21.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ntfy
            port:
              name: http

  - host: push.cloud.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ntfy
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ntfy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  policyTypes:
    - Ingress
    - Egress
  ingress:
  # Allow Ingress
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: traefik
    ports:
    - protocol: TCP
      port: 8080


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi