
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/version: 1.6.1
    helm.sh/chart: prometheus-node-exporter-4.23.2
    jobLabel: node-exporter
    release: release-name
    app.kubernetes.io/name: envoy
    app.kubernetes.io/instance: external-http
spec:
  endpoints:
  - honorLabels: true
    port: admin
    path: /stats/prometheus
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - external-http
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy
      app.kubernetes.io/instance: external-http