apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-node-exporter
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
    release: monitoring
spec:
  staticConfigs:
  - labels:
      job: node-exporter
    targets:
      - 10.0.0.13:9100
      - kube-state-metrics.10.0.0.16.nip.io
      - 10.0.0.14:9100
      - 10.0.0.22:9100
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-kubestate-metrics
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
    release: monitoring
spec:
  staticConfigs:
  - labels:
      job: kube-state-metrics
    targets:
      - kube-state-metrics.10.0.0.16.nip.io
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: external-smartctl-exporter
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
    release: monitoring
spec:
  staticConfigs:
  - labels:
      job: smrtctl-exporter
    targets:
      - 10.0.0.19:9633
