# default promtail values: https://github.com/grafana/helm-charts/blob/promtail-6.2.3/charts/promtail/values.yaml
config:
  logLevel: info
  serverPort: 3101
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenant_id: buc
  snippets:
    extraScrapeConfigs: |
      - job_name: journal
        journal:
          path: /var/log/journal
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__hostname']
            target_label: 'hostname'

# Mount journal directory into Promtail pods
extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal

extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true
