# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: loki-datasource
#   labels:
#     grafana_datasource: "1"
# data:
#   datasource.yaml: |-
#     apiVersion: 1
#     datasources:
#     - name: Loki
#       type: loki
#       isDefault: false
#       access: proxy
#       url: http://loki-gateway
#       version: 1
#       jsonData:
#         httpHeaderName1: X-Scope-OrgID
#       secureJsonData:
#         httpHeaderValue1: buc


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-metrics
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: loki
    release: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: "http-metrics"
  selector:
    matchLabels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/name: loki
