
# loki:
#   commonConfig:
#     replication_factor: 1
#   storage:
#     type: 'filesystem'
# singleBinary:
#   replicas: 1



loki:
  auth_enabled: false
  limits_config:
    retention_period: 1d
    split_queries_by_interval: 1h
  compactor:
    retention_enabled: true
    compaction_interval: 10m
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: filesystem
  commonConfig:
    replication_factor: 1 # needed since we only run one Loki instance
  # rulerConfig:
  #   alertmanager_url: http://monitoring-kube-prometheus-alertmanager.monitoring:9093
  #   storage:
  #     type: local
  #     local:
  #       directory: /var/loki/rules
    ring:
      kvstore:
        store: inmemory
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: 2024-08-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  query_scheduler:
    max_outstanding_requests_per_tenant: 4096
  frontend:
    max_outstanding_per_tenant: 4096
  query_range:
    parallelise_shardable_queries: true

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: false
chunksCache:
  # default is 500MB, with limited memory keep this smaller
  writebackSizeLimit: 10MB

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  # extraVolumeMounts:
  #   - name: rules
  #     mountPath: /var/loki/rules/socradev
  # extraVolumes:
  #   - name: rules
  #     configMap:
  #       name: alerting-rules
  persistence:
    enabled: true
    size: 3Gi
    storageClass: local-path
    enableStatefulSetAutoDeletePVC: true

  # resources:
  #   requests:
  #     cpu: 2
  #     memory: 2Gi
  extraEnv:
    # Keep a little bit lower than memory limits
    - name: GOMEMLIMIT
      value: 3750MiB

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0


# Example Values from Grafana
# Source: https://github.com/grafana/loki/blob/main/production/helm/loki/single-binary-values.yaml
# ---
# loki:
#   ingester:
#     chunk_encoding: snappy
#   tracing:
#     enabled: true
#   querier:
#     # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
#     max_concurrent: 2
