apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster
    kind: ClusterSecretStore
  target:
    name: oidc-provider-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: oidc/green-prod