apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - https://github.com/thomasbuchinger/syncthing-operator/config/default?timeout=120&ref=main
- syncthing-app.yaml
- syncthing-pv.yaml