
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing-metrics
  namespace: syncthing
spec:
  rules:
  - host: "syncthing.10.0.0.21.nip.io"
    http:
      paths:
      - path: "/metrics"
        pathType: Prefix
        backend:
          service:
            name: syncthing
            port:
              name: http
