apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-datasource
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      isDefault: false
      url: http://tempo:3100
      version: 1
