---
tempo:
  serviceMonitor:
    enabled: true
  metricsGenerator:
    enables: true
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

tempoQuery:
  repository: grafana/tempo-query
  enabled: true
  service:
    port: 16686
  ingress:
    enabled: true
    path: /
    hosts:
    - tracing.buc.sh
    - tracing.10.0.0.21.nip.io
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
minio:
  enabled: false
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false