apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-helm
  namespace: argocd
spec:
  project: apps
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.9
    helm:
      releaseName: external-secrets
      parameters:
      - name: serviceAccount.name
        value: external-secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
