---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credantials
  namespace: csi-mountpoint-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-evergreen
    kind: ClusterSecretStore
  target:
    name: eso-s3-credentials
    creationPolicy: Owner
  data:
  - secretKey: key_id
    remoteRef:
      key: static-secrets
      property: s3_accesskey
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: access_key
    remoteRef:
      key: static-secrets
      property: s3_secretkey
      conversionStrategy: Default
      decodingStrategy: None