helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  # version: 54.2.2
  # BUG: release-name must be the same as namespace. Or Prometheus' ServiceMonitor will be wrong
  releaseName: monitoring
  namespace: monitoring
  valuesFile: values.yaml
  includeCRDs: true
