
grafana:
  enabled: false
  forceDeployDatasources: true
  forceDeployDashboards: true
  defaultDashboardsEnabled: true

defaultRules.rules.kubeProxy: false
kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi
    # securityContext:
    #   runAsGroup: 65534
    #   runAsNonRoot: true
    #   runAsUser: 65534
    #   fsGroup: 65534

    # - name: "init-chmod-data"
    #   image: "busybox"
    #   command: ["chmod", "-R", "o+rw", /var/prometheus/data]
    #   volumeMounts:
    #   - name: prometheus-monitoring-kube-prometheus-prometheus-db-prometheus-monitoring-kube-prometheus-prometheus-0
    #     mountPath: /var/prometheus/data
    securityContext:
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000