
grafana:
  enabled: false
  forceDeployDatasources: true
  forceDeployDashboards: true
  defaultDashboardsEnabled: true

defaultRules.rules.kubeProxy: false
kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    # storageSpec:
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: local-path
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 3Gi
    # # securityContext:
    # #   runAsGroup: 65534
    # #   runAsNonRoot: true
    # #   runAsUser: 65534
    # #   fsGroup: 65534
    # securityContext:
    #   runAsGroup: 2000
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   fsGroup: 2000