
grafana:
  enabled: false
  forceDeployDatasources: true
  forceDeployDashboards: true
  defaultDashboardsEnabled: true

defaultRules.rules.kubeProxy: false
kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      runAsGroup: 0
      fsGroup: 0
    
    # securityContext:
    #   runAsGroup: 65534
    #   runAsNonRoot: true
    #   runAsUser: 65534
    #   fsGroup: 65534
    # initContainers:
    # - name: "init-chmod-data"
    #   image: "busybox"
    #   command:
    #   - sh
    #   - -c
    #   - 'id; ls -ldR /prometheus'
    #   # command: ["chmod", "-R", "o+rw", /var/prometheus/data]
    #   volumeMounts:
    #   - name: prometheus-monitoring-kube-prometheus-prometheus-db
    #     mountPath: /prometheus
    # securityContext:
    #   runAsGroup: 2000
    #   runAsNonRoot: true
    #   runAsUser: 1000
    #   fsGroup: 2000