
grafana:
  enabled: false
  forceDeployDatasources: true
  forceDeployDashboards: true
  defaultDashboardsEnabled: true

defaultRules.rules.kubeProxy: false
kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    securityContext:
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534
