---
apiVersion: v1
kind: Namespace
metadata:
  name: external-homelabapi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-homelab-api
  namespace: external-homelabapi
  labels:
    app.kubernetes.io/name: homelab-api
    app.kubernetes.io/instance: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homelap-api
      app.kubernetes.io/instance: external
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homelap-api
        app.kubernetes.io/instance: external
    spec:
      containers:
      - name: homelab-api
        image: ghcr.io/thomasbuchinger/homelab-api:main
        imagePullPolicy: Always
        env:
        - name: MODE
          value: public
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/livez
            port: 8080
        readinessProbe:
          httpGet:
            path: /api/readyz
            port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: external-homelab-api
  namespace: external-homelabapi
spec:
  selector:
    app.kubernetes.io/name: homelab-api
    app.kubernetes.io/instance: external
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: homepage
#   namespace: homepage
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare-dns
# spec:
#   tls:
#   - hosts:
#     - status.buc.sh
#     secretName: cert-status-buc-sh
#   rules:
#   - host: status.buc.sh
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: homepage
#             port:
#               number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-homelab-api-http
  namespace: external-homelabapi
spec:
  rules:
  - host: api.10.0.0.21.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-homelab-api
            port:
              number: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-homepage-egress
  namespace: external-homelabapi
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: homelab-api
      app.kubernetes.io/instance: external
  policyTypes:
    - Egress
    # - Ingress
  egress:
  - to:
    - ipBlock:
        cidr: "0.0.0.0/0"
  # ingress:
  # # Allow Ingress
  # - from:
  #   - namespaceSelector:
  #       matchLabels:
  #         kubernetes.io/metadata.name: traefik
  #   ports:
  #   - protocol: TCP
  #     port: 8080

