
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-keep
  labels:
    app.kubernetes.io/instance: local-path-storage
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer