---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  settings.yml: |
    security:
      enableLogin: false # set to 'true' to enable login
      csrfDisabled: true

    system:
      defaultLocale: 'en-US' # Set the default language (e.g. 'de-DE', 'fr-FR', etc)
      googlevisibility: false # 'true' to allow Google visibility (via robots.txt), 'false' to disallow
    #  customStaticFilePath: '/customFiles/static/' # Directory path for custom static files
    ui:
      appName: PDF Tools
      homeDescription: "Hosted on Kubernetes"
      appNameNavbar: PDF

    #endpoints:
    #  toRemove: [] # List endpoints to disable (e.g. ['img-to-pdf', 'remove-pages'])
    #  groupsToRemove: [] # List groups to disable (e.g. ['LibreOffice'])

    metrics:
      enabled: true # 'true' to enable Info APIs endpoints (view http://localhost:8080/swagger-ui/index.html#/API to learn more), 'false' to disable

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  labels:
    app.kubernetes.io/name: s-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: s-pdf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: s-pdf
    spec:
      containers:
      - name: s-pdf
        image: ghcr.io/stirling-tools/s-pdf:0.28.2-fat
        # command:
        # - bash
        # - -c
        # - cp -f /myconfigs/settings.yml /configs/settings.yml && exec java -jar /app.jar
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: DOCKER_ENABLE_SECURITY
          value: "false"
        - name: SECURITY_ENABLELOGIN
          value: "false"
        - name: SECURITY_CSRFDISABLED
          value: "true"
        - name: SYSTEM_DEFAULTLOCALE
          value: "en-US"
        - name: SYSTEM_GOOGLEVISIBILITY
          value: "false"
        - name: UI_APPNAME
          value: PDF-Tools
        - name: UI_HOMEDESCRIPTION
          value: Hosted on Kubernetes
        - name: UI_APPNAMENAVBAR
          value: PDF
        - name: METRICS_ENABLED
          value: "true"
        volumeMounts:
        - name: ocr
          mountPath: /usr/share/tesseract-ocr/4.00/tessdata
        # - name: configs
        #   mountPath: /configs
        livenessProbe:
          tcpSocket:
            port: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 5m
            memory: 300Mi
          limits: {}
        securityContext:
          allowPrivilegeEscalation: false
          # runAsUser: 1000
          # runAsGroup: 1000
          capabilities:
            add:
            - CHOWN
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 1000
        # runAsNonRoot: true
      volumes:
      - name: ocr
        emptyDir: {}
      - name: configs
        configMap:
          name: app-config

---
kind: Service
apiVersion: v1
metadata:
  name: stirling-pdf
spec:
  selector:
    app.kubernetes.io/name: s-pdf
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-pdf
spec:
  rules:
  - host: pdf.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stirling-pdf
            port:
              number: 8080
  - host: pdf.10.0.0.21.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stirling-pdf
            port:
              number: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spdf
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: s-pdf
  policyTypes:
    - Ingress
    - Egress
  ingress:
  # Allow Ingress
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: traefik
    ports:
    - protocol: TCP
      port: 8080
