---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  labels:
    app.kubernetes.io/name: s-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: s-pdf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: s-pdf
    spec:
      containers:
      - name: s-pdf
        image: "ghcr.io/frooodle/s-pdf:latest"
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: DOCKER_ENABLE_SECURITY
          value: "false"
        volumeMounts:
        - name: ocr
          mountPath: /usr/share/tesseract-ocr/4.00/tessdata
        livenessProbe:
          tcpSocket:
            port: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 5m
            memory: 300Mi
          limits: {}
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: ocr
        emptyDir: {}
      - name: configs
        emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: stirling-pdf
spec:
  selector:
    app.kubernetes.io/name: s-pdf
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-pdf
spec:
  rules:
  - host: pdf.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stirling-pdf
            port:
              number: 8080
  - host: pdf.10.0.0.21.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stirling-pdf
            port:
              number: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: spdf
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: s-pdf
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow Ingress
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 8080
