---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway-mtls
spec:
  gatewayClassName: gwclass-external
  listeners:
  - &mtls
    hostname: echo.mtls.buc.sh
    name: echo
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: cert-cloud-buc-sh
    allowedRoutes:
      namespaces:
        from: All
  - <<: *mtls
    hostname: cams.mtls.buc.sh
    name: frigate

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: mtls-policy
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external-gateway
    sectionName: mtls
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external-gateway-mtls
  tls:
    clientValidation:
      optional: false
      caCertificateRefs:
      - kind: "Secret"
        group: ""
        name: "root-ca-mtls"
  headers:
    xForwardedClientCert:
      mode: SanitizeSet
      certDetailsToAdd:
      - Subject
      - DNS
      - URI