kind: Kustomization

namespace: monitoring
helmCharts:
- name: prometheus-statsd-exporter
  repo: oci://ghcr.io/prometheus-community/charts
  version: 1.0.0
  releaseName: statsd-exporter
  namespace: monitoring
  valuesFile: values.yaml
  
resources:
- nodeport.yaml