kind: Kustomization
helmCharts:
- name: redis
  # repo: https://charts.bitnami.com/bitnami
  repo: oci://registry-1.docker.io/bitnamicharts/
  releaseName: redis-ephemeral
  version: 22.0.6
  namespace: paperless
  includeCRDs: true
  valuesInline:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: false

resources:
- paperless-app.yaml
- paperless-pv.yaml