apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  releaseName: redis-ephemeral
  namespace: paperless
  includeCRDs: true
  valuesInline:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: false

resources:
- paperless-app.yaml
- k8s-apps-pv.yaml