kind: Kustomization
helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  releaseName: redis-ephemeral
  version: 21.2.5
  namespace: paperless
  includeCRDs: true
  valuesInline:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: false

resources:
- paperless-app.yaml
- paperless-pv.yaml