apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-env
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
data:
  COMPOSE_PROJECT_NAME: paperless
  PAPERLESS_REDIS: redis://redis-ephemeral-headless
  # Languages to install
  # PAPERLESS_OCR_LANGUAGES: eng deu
  # Lanugaes to use
  PAPERLESS_OCR_LANGUAGE: deu
  USERMAP_UID: "1001"
  USERMAP_GID: "1001"
  PAPERLESS_TIME_ZONE: Europe/Vienna
  PAPERLESS_DBENGINE: sqlite
  PAPERLESS_FILENAME_FORMAT: '{created_year}/{correspondent}/{created}_{title}'
  # Database and other internals
  PAPERLESS_DATA_DIR: /data/data
  # Storage for documents
  PAPERLESS_MEDIA_ROOT: /data/media
  # PAPERLESS_TRASH_DIR: /data/media/Trash
  # Not really used, but we put it on the PV anyway
  PAPERLESS_CONSUMPTION_DIR: /data/in
  PAPERLESS_PORT: "8000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: paperless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paperless
    spec:
      securityContext:
        # runAsGroup: 1001
        runAsNonRoot: false
        # runAsUser: 1001
        fsGroup: 1001
      automountServiceAccountToken: true
      containers:
      - name: paperless
        image:  ghcr.io/paperless-ngx/paperless-ngx:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: paperless-env
        ports:
        - name: http
          containerPort: 8000
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          tcpSocket:
            port: 8000
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          tcpSocket:
            port: 8000
        resources:
          requests:
            cpu: 50m
            memory: 400Mi
          limits: {}
        securityContext:
          # allowPrivilegeEscalation: false
          capabilities:
          #   # add:
          #   # - CHOWN
          #   # # - SET_UID
          #   # # - SET_GID
          #   # - FOWNER
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /data
          name: paperless-data
      volumes:
      - name: paperless-data
        emptyDir: {}


# PVs: data
# or SQlite: litestream+s3?

# tls-Ingress: paperless.buc.sh
# ESO Secret: Certificate, username/password

---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
spec:
  selector:
    app.kubernetes.io/name: paperless
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-http
  namespace: paperless
  labels:
    app.kubernetes.io/name: paperless
spec:
  rules:
  - host: paperless.prod.buc.sh
    http:
      paths:
      - backend:
          service:
            name: paperless
            port:
              number: 8000
        path: /
        pathType: Prefix
  - host: paperless.10.0.0.21.nip.io
    http:
      paths:
      - backend:
          service:
            name: paperless
            port:
              number: 8000
        path: /
        pathType: Prefix
