---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-nfs
  namespace: paperless
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: paperless-nfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-nfs
spec:
  capacity:
    storage: 4Ti
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  nfs:
    server: 10.0.0.20
    path: /mnt/raidpool/kubernetes/paperlessngx
  mountOptions:
  - nfsvers=4.2
  - retrans=3
  - ac         # Fileattribute cache
  - fsc        # File cache
  # # if NFS server is unreachable, block all IO
  - hard
  - timeo=600
