---
apiVersion: v1
kind: Namespace
metadata:
  name: mediarr

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: config-volume
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 1Gi