namespace: mediarr

patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1

resources:
- common.yaml
- jelly-exporter.yaml
- jellyseer.yaml
- radarr.yaml
- sonarr.yaml
- prowlarr.yaml
- sabnzbd.yaml
- qbittorrent.yaml

configMapGenerator:
- name: arr-config
  envs:
  - arr-config.env
- name: config-files
  files:
  - qbittorrent.conf
