namespace: mediarr

resources:
- common.yaml
- jellyseer.yaml
- radarr.yaml
- prowlarr.yaml
- sabnzbd.yaml

configMapGenerator:
- name: arr-config
  envs:
  - arr-config.env
- name: config-files
  files:
  - sabnzbd.ini