---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          # limits:
          #   memory: "128Mi"
        ports:
        - containerPort: 9696
          name: http
        env:
        - name: TZ
          value: Europe/Vienna
        - name: PUID
          value: "99"
        - name: PGID
          value: "100"
        envFrom:
        - configMapRef:
            name: arr-config
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        securityContext:
          readOnlyRootFilesystem: false
          runAsNonRoot: false
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - SETGID
            - SETUID
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: config
          mountPath: "/config"
          subPath: prowlarr
      - name: prowlarr-exporter
        image: ghcr.io/onedr0p/exportarr:v2.3
        imagePullPolicy: IfNotPresent
        args:
          - prowlarr
        env:
          - name: PORT
            value: "9100"
          - name: URL
            value: "http://prowlarr:9696"
          - name: APIKEY
            valueFrom:
              configMapKeyRef:
                name: arr-config
                key: PROWLARR__AUTH__APIKEY
        ports:
          - name: metrics
            containerPort: 9100
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: metrics
          failureThreshold: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 1m
            memory: 64Mi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: mediarr-config

---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  selector:
    app: prowlarr
  ports:
  - name: http
    port: 9696
    targetPort: http
  - name: metrics
    port: 9100
    targetPort: metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prowlarr-exporter
  labels:
    app: prowlarr
spec:
  selector:
    matchLabels:
      app: prowlarr
  endpoints:
    - port: metrics
      interval: 5m
      scrapeTimeout: 90s
      path: /metrics

