apiVersion: v1
kind: Namespace
metadata:
  name: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-test
  labels:
    app: pvc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-test
  template:
    metadata:
      labels:
        app: pvc-test
    spec:
      containers:
      - name: pvc-test
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: test-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: nfs
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: nfs-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  nfs:
    server: 10.0.0.20
    path: /mnt/raidpool/kubernetes
    readOnly: true
  mountOptions:
    - nfsvers=4.2
