apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: 0.5.9
  releaseName: external-secrets
  namespace: external-secrets
  valuesFile: values.yaml
  includeCRDs: true

resources:
- secret-id-sealed.yaml
- secret-stores.yaml