apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-id
  namespace: external-secrets
spec:
  encryptedData:
    secretid: AgAxRh4+00MaRjSe2YyQ2mNqi7WfD1Le7moEECkSWUz5LK0PRuZ/d4k+H1Ep6PG1C8/2FrGHzKCKojWx4DKceU71523wCf2ZYTBwmXNW7UMFqpYs6KYvxHdgl0HMLzSMJbGGYfRXgQBcp1YQOuDayweEQALcvTm+WR2PG/tX2ZW9MEuRpi5oP5GeGBk2awFPbErzPwa3FCByfSSAzCJxBMwKJRlUgJ1G+jG7A31NXhgONfFZDhppDmbN1DffP4FBIKsim2zA2NUtWJwI5ubpHzwxj6AeQuP7Le8PZh8N+iIBtCfb7fy94CDu/7EVtCR5JnXxLh+wzQq7wrb7so7d2EpetQU+gUhscUr6TXS+BMjR4dVUG/fromqMQArZJqmhm9o+eI6MhtEokC1m9w6uvDb1hHFr14MoneT2xa5K/Ga5sqqIIa/cc9kNBIP/b4y/+WNR6B62dVAMqyn21fLEpqGE7Xro/nagY/qulqsIn2JQ2JzT0jDFxzfoHPvWtz8Bn4RuhAlRQpVaZRBOsMFJYMKwbE5qVaKb0adsbjgLPwe1BJTcCGKp9KdvoxaGZcLz8UQst5G5q8A6tbZTCQhbYNAPJALW41BCddowjth0sQHWwKReXLUqm6hmqv2aB8VR/zHqi42cyRyAx7yC7F5qW57lqan4Q5orYHxWoHMbEaUHp0u/YXbdTQUHeAkw1fyhH14PVJ9QIeTxWUSs9vF1msr4KcoaNm8zSjNNiWTo5zM15cWlyk4=
  template:
    metadata:
      creationTimestamp: null
      name: secret-id
      namespace: external-secrets

