apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-approle-cluster
  namespace: external-secrets
  annotations:
     argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    vault:
      server: "https://vault.buc.sh"
      path: "cluster/"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: prod
          secretRef:
            name: "vault-secretid"
            key: "secretid"
