{
 "title": "HomeLAB Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "External Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"https-10443\", envoy_response_code_class=~\"2|3|4|5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests BY HOST",
   "type": "table",
   "description": "HTTP Requests forwarded to the Upstream Service",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(envoy_cluster_name, envoy_response_code) (envoy_cluster_external_upstream_rq)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "envoy_server_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix!~\"admin|template\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix!~\"admin|template\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix!~\"admin|template\"}[1m]) * -1",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix!~\"admin|template\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"http-10080\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"https-10443\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"https-10444\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"https-10445\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"https-10445\", envoy_response_code_class=~\"2|3|4|5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "envoy_server_days_until_first_cert_expiring",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=~\"https-10444\", envoy_response_code_class=~\"2|3|4|5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AccessLog - Blocked",
   "type": "logs",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "{container=\"envoy\"} |= `\"path\":` | json | response_code !~ `2..` | line_format `{{ .x_forwarded_for }} {{.response_flags}} {{ .response_code }} | {{.authority}}{{ .path }}`"
    }
   ]
  },
  {
   "title": "Access Logs - Top Paths",
   "type": "table",
   "description": "Top 5 Paths accessed by IP Address",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "topk by(x_forwarded_for) (5, sum by(path, x_forwarded_for) (count_over_time({container=\"envoy\"} | json | __error__=`` [$__range])))"
    }
   ]
  },
  {
   "title": "AccessLog - Success",
   "type": "logs",
   "description": "AccessLog for Successful Requests",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{container=\"envoy\"} |= `\"path\"` | json | response_code =~ `2..` | line_format `      {{.response_code}} - {{.x_forwarded_for}} | {{.authority}}{{.path}}`"
    }
   ]
  },
  { "title": "HomeLAB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(node_time_seconds - node_boot_time_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    { "expr": "sum(kube_pod_status_phase)", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(country) (count_over_time({app=\"envoy\"} |= `geo` | json country=\"x_geo_country\" [$__auto]))"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "sum by(latitude, longitude, city) (homelabapi_geoip_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_btrfs_device_unused_bytes{device!~\"loop3|loop2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "description": "Top 10 Hosts used to access the wesite",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "sum by(authority) (count_over_time({container=\"envoy\"} | json | __error__=`` [$__range]))"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  { "type": "alertlist", "gridPos": { "h": 10, "w": 22, "x": 2, "y": 31 } }
 ]
}