apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

helmCharts:
- name: grafana
  repo: https://grafana.github.io/helm-charts
  # version: 6.50.0
  releaseName: grafana
  namespace: monitoring
  valuesFile: values.yaml
  includeCRDs: true

resources:
- resources.yaml

configMapGenerator:
- name: homelab-dashboards
  files:
    - HomeLAB-Dashboard.json

generatorOptions:
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "HomeLAB"

