kind: Kustomization

helmCharts:
- name: grafana
  repo: https://grafana.github.io/helm-charts
  # version: 6.50.0
  releaseName: grafana
  namespace: monitoring
  valuesFile: values.yaml
  includeCRDs: true

resources:
- resources.yaml

configMapGenerator:
- name: homelab-dashboards
  namespace: monitoring
  files:
  - HomeLAB-Dashboard.json
  - dashboard=landing.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "HomeLAB"

