
serviceMonitor: {}
networkPolicy:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: false

admin:
  existingSecret: grafana-admin-cred
  userKey: username
  passwordKey: password

datasources:
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-kube-prometheus-prometheus:9090
     access: proxy
     isDefault: true
dashboards:
  default:
    custom-dashboard:
      # This is a path to a file inside the dashboards directory inside the chart directory
      file: dashboard-landing.json
    cluster-dashboard:
      gnetId: 315
      datasource: Prometheus