
serviceMonitor: {}
networkPolicy:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: false

admin:
  existingSecret: grafana-admin-cred
  userKey: username
  passwordKey: password

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'kube-prometheus-dashboards'
      orgId: 1
      folder: 'Custom'
      type: file
      disableDeletion: false
      editable: true
      allowUiUpdates: true
      options:
        path: /tmp/dashboards/
    - name: 'custom-dashboards'
      orgId: 1
      folder: 'Grafana.com'
      type: file
      disableDeletion: false
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/custom

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://monitoring-kube-prometheus-prometheus:9090
      access: proxy
      isDefault: true
  loki.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      isDefault: false
      access: proxy
      url: http://loki-gateway
      version: 1
      jsonData:
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        httpHeaderValue1: buc
  tempo.yaml:
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      isDefault: false
      url: http://tempo:3200
      version: 1
dashboards:
  custom:
    cluster-dashboard:
      gnetId: 315
      datasource: Prometheus
    envoy-dashboard:
      gnetId: 11021
      datasource: Prometheus
    nodeexporter-full:
      gnetId: 1860
      datasource: Prometheus

assertNoLeakedSecrets: false
grafana.ini:
  server:
    root_url: https://grafana.buc.sh
  # auth:
  #   disable_login_form: true
  # auth.basic:
  #   enabled: false
  auth.generic_oauth:
    name: BUC Login
    enabled: true
    client_id: login
    client_secret: notaSecretDexisLocal
    scopes: openid email profile groups offline_access
    auth_url: https://dex.buc.sh/auth
    token_url: https://dex.buc.sh/token
    api_url: https://dex.buc.sh/userinfo


    allow_assign_grafana_admin: true
    role_attribute_path: "'GrafanaAdmin'"
  users:
    auto_assign_org: true
    auto_assign_org_role: Admin
      