
serviceMonitor: {}
networkPolicy:
  enabled: true
resources:
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: false

admin:
  existingSecret: grafana-admin-cred
  userKey: username
  passwordKey: password

datasources: {}
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards: {}