port: 8080
log: /dev/stdout
log_rotation: ""
error_log: /dev/stderr
title: "BUC Public Files"
vfs:
  children:
    - name: private
      can_see: true
    - name: protected
      can_read: "*"
    - name: public
      children:
        - source: /template/README.html
    - source: /app/myDisk/uploads
      children: []
    - name: README
      url: /public/README.html
open_browser_at_start: false
localhost_admin: false
proxies: 1
accounts:
  guest:
    disable_password_change: true
    password: why-guest-no-password