kind: Kustomization

configMapGenerator:
- name: hfs-config
  namespace: external-hfs
  literals:
  - guest_password=why-guest-no-password
  files:
  - hfs-config.yaml
  - README.html

resources:
- deploy.yaml
- pv.yaml
- ingress.yaml