---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hfs-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hfs-uploads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-data
  namespace: external-hfs
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: external-hfs-nas-data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-hfs-nas-data
spec:
  capacity:
    storage: 4Ti
  accessModes:
  - ReadWriteMany
  - ReadOnlyMany
  nfs:
    server: 10.0.0.19
    path: /mnt/user/
  mountOptions:
  - nfsvers=4.2
  - retrans=3
  - ro         # ReadOnly
  - ac         # Fileattribute cache
  - fsc        # File cache
  # # if NFS server is unreachable, block all IO
  - hard
  - timeo=600