---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak

---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: sso
spec:
  instances: 1
  db:
    vendor: dev-file
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
  ingress:
    enabled: false
  #   tlsSecret: example-tls-secret
  hostname:
    hostname: https://sso.cloud.buc.sh
    admin: https://sso-admin.mtls.buc.sh/admin
    strict: false
    backchannelDynamic: true
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
