---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak

---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: sso
spec:
  instances: 1
  bootstrapAdmin:
    user:
      secret: "credential-sso-keycloak"
  db:
    vendor: dev-file
  http:
    httpEnabled: true
    httpPort: 8080
    # httpsPort: 8443
  networkPolicy:
    enabled: false
  ingress:
    enabled: false
  #   tlsSecret: example-tls-secret
  hostname:
    hostname: https://sso.cloud.buc.sh
    admin: https://keycloak.buc.sh/
    strict: false
    backchannelDynamic: true
  additionalOptions:
  - name: hostname-debug
    value: "true"
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  unsupported:
    podTemplate:
      spec:
        containers:
        - volumeMounts:
          - name: data
            mountPath: /opt/keycloak/data/h2
        volumes:
        - name: data
          emptyDir: {}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-creds
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: k8s-evergreen
    kind: ClusterSecretStore
  target:
    name: credential-sso-keycloak
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: static-secrets
      property: cred_admin_user
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: password
    remoteRef:
      key: static-secrets
      property: cred_admin_password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: ADMIN_USERNAME
    remoteRef:
      key: static-secrets
      property: cred_admin_user
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: ADMIN_PASSWORD
    remoteRef:
      key: static-secrets
      property: cred_admin_password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "local-path"
