
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-cert
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: k8s-evergreen
    kind: ClusterSecretStore
  target:
    name: cert-keycloak-buc-sh
    creationPolicy: Owner
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: cert-keycloak-buc-sh

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-admin-interface
spec:
  tls:
  - hosts:
      - keycloak.buc.sh
    secretName: cert-keycloak-buc-sh
  rules:
  - host: "keycloak.buc.sh"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: sso-service
            port:
              name: http



# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: sso-admin-mtls-buc-sh
# spec:
#   parentRefs:
#   - group: gateway.networking.k8s.io
#     kind: Gateway
#     name: external-gateway-mtls
#     namespace: external-gateway
#   hostnames:
#   - "sso-admin.mtls.buc.sh"
#   rules:
#   - backendRefs:
#     - group: ""
#       kind: Service
#       name: sso-service
#       port: 8080
#       weight: 1
#     matches:
#     - path:
#         type: PathPrefix
#         value: /

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sso-cloud-buc-sh
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external-gateway
    namespace: external-gateway
  hostnames:
  - "sso.cloud.buc.sh"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: sso-service
      port: 8080
      weight: 1
    matches:
    - path:
        type: Exact
        value: /
    - path:
        type: PathPrefix
        value: /realms
    - path:
        type: PathPrefix
        value: /resources
    - path:
        type: PathPrefix
        value: /.well-known
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /realms/master
#     filters:
#     - type: ExtensionRef
#       extensionRef:
#         group: gateway.envoyproxy.io
#         kind: HTTPRouteFilter
#         name: 403-denied

# ---
# apiVersion: gateway.envoyproxy.io/v1alpha1
# kind: HTTPRouteFilter
# metadata:
#   name: 403-denied
# spec:
#   directResponse:
#     contentType: text/html
#     statusCode: 404
#     body:
#       type: Inline
#       inline: <html><head><meta charset="UTF-8"></head><body><p style="margin-top:10%;font-size:4em;font-family:'Courier New', Courier, monospace;" align="center">Access Denied / Not allowed on Public Interface</p></body></html>

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: lua-geoip-block
spec:
  targetRefs:
  # - group: gateway.networking.k8s.io
  #   kind: HTTPRoute
  #   name: sso-admin-mtls-buc-sh
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: sso-cloud-buc-sh
  lua:
  - type: Inline
    inline: |
      function envoy_on_request(request_handle)
        local allowed_countried = { AT=true, DE=true, CH=true, HR=true, IT=true }
        if not allowed_countried[request_handle:headers():get("X-Geo-Country")] then
          request_handle:respond(
            {[":status"] = "451"}, "Not available in your country")
        end
      end

