
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sso-admin-mtls-buc-sh
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external-gateway-mtls
    namespace: external-gateway
  hostnames:
  - "sso-admin.mtls.buc.sh"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: sso-service
      port: 9000
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sso-mtls-buc-sh
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external-gateway-mtls
    namespace: external-gateway
  hostnames:
  - "sso.mtls.buc.sh"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: sso-service
      port: 8443
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: lua-geoip-block
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: sso-admin-mtls-buc-sh
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: sso-mtls-buc-sh
  lua:
  - type: Inline
    inline: |
      function envoy_on_request(request_handle)
        local allowed_countried = { AT=true, DE=true, CH=true, HR=true, IT=true }
        if not allowed_countried[request_handle:headers():get("X-Geo-Country")] then
          request_handle:respond(
            {[":status"] = "451"}, "Not available in your country")
        end
      end

