apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-helm
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.6.8
    helm:
      releaseName: sealed-secrets
      parameters:
      - name: secretName
        value: sealed-secrets-private-key
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
