


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ui
data:
  app.ini: |
    [server]
    HttpPort          = 9000
    RunMode           = debug
    JwtSecret         = 
    NodeSecret        = 384c2355-aae3-4954-a345-cca013a0eaff
    HTTPChallengePort = 9180
    Email             = admin@example.com
    Database          = database
    StartCmd          = login
    CADir             = 
    Demo              = false
    PageSize          = 10
    GithubProxy       = 
    
    
    [nginx]
    AccessLogPath = 
    ErrorLogPath  = 
    ConfigDir     = 
    PIDPath       = 
    ReloadCmd     = 
    RestartCmd    = 

    [openai]
    BaseUrl = 
    Token   = 
    Proxy   = 
    Model   = 

    [git]
    Url                = 
    AuthMethod         = 
    Username           = 
    Password           = 
    PrivateKeyFilePath = 

  dump.sql: |
    PRAGMA foreign_keys=OFF;
    BEGIN TRANSACTION;
    CREATE TABLE `auth_tokens` (`token` text);
    CREATE TABLE IF NOT EXISTS "chat_gpt_logs" (`name` text,`content` text);
    CREATE TABLE IF NOT EXISTS "config_backups" (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`file_path` text,`content` text,PRIMARY KEY (`id`));
    CREATE TABLE IF NOT EXISTS "auths" (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`password` text,PRIMARY KEY (`id`));
    CREATE TABLE IF NOT EXISTS "dns_credentials" (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`config` text,`provider` text,PRIMARY KEY (`id`));
    CREATE TABLE IF NOT EXISTS "certs" (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`domain` text, `domains` text[], `filename` text, `ssl_certificate_path` text, `ssl_certificate_key_path` text, `auto_cert` integer, `name` text, `log` text, `challenge_method` text, `dns_credential_id` integer,PRIMARY KEY (`id`));
    CREATE TABLE IF NOT EXISTS "sites" (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`path` text,`advanced` numeric,PRIMARY KEY (`id`));
    CREATE TABLE IF NOT EXISTS "environments" (`id` integer,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`url` text,`token` text,PRIMARY KEY (`id`));
    CREATE INDEX `idx_config_backups_deleted_at` ON `config_backups`(`deleted_at`);
    CREATE INDEX `idx_auths_deleted_at` ON `auths`(`deleted_at`);
    CREATE INDEX `idx_dns_credentials_deleted_at` ON `dns_credentials`(`deleted_at`);
    CREATE INDEX `idx_certs_deleted_at` ON `certs`(`deleted_at`);
    CREATE INDEX `idx_sites_deleted_at` ON `sites`(`deleted_at`);
    CREATE INDEX `idx_environments_deleted_at` ON `environments`(`deleted_at`);

    INSERT INTO auths VALUES(1,'2021-10-13 11:08:51.586009312+08:00','2023-11-01 17:50:15.232273307+00:00',NULL,'admin','$2a$10$tGVXZYokfAyf0Qf0/5kkMex8MnF5AH9cd7kd1vr/t9CK.UV.FwZia');
    INSERT INTO auths VALUES(2,'2023-11-01 17:38:30.037216134+00:00','2023-11-01 17:38:30.037216134+00:00','2023-11-01 17:41:11','admin','$2a$10$Tz9WdkTrLPPSilvh2FsGLeqzLHjRIwV4BSGFa1mwneveSvGlw41l6');
    INSERT INTO auths VALUES(3,'2023-11-01 17:50:43.969476629+00:00','2023-11-01 17:50:43.969476629+00:00',NULL,'buc','$2a$10$5m1TXlL2MEpcIqDi.tf/yOSz569s2ASME0zlfYipd7wDwFpjGeIZm');
    INSERT INTO auth_tokens VALUES('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJleHAiOjE2OTg5NDY3MjR9.w122oUFxiIznsW9llyFeHsrSTQCLvEmxCi9lTkHh5nw');
    INSERT INTO chat_gpt_logs VALUES('/etc/nginx/sites-available/test',NULL);
    COMMIT;
