---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-http
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: external-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: external-http
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: external-http
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        # image: cgr.dev/chainguard/nginx:latest
        imagePullPolicy: IfNotPresent
        env: []
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          # failureThreshold: 3
          # periodSeconds: 10
          # successThreshold: 1
          # timeoutSeconds: 1
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
          limits: {}
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     add:
        #     - NET_BIND_SERVICE
        #     drop:
        #     - ALL
        #   seccompProfile:
        #     type: RuntimeDefault
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d
        - name: tmpdir
          mountPath: /var/cache/nginx
      - name: nginx-ui
        image: busybox
        imagePullPolicy: IfNotPresent
        env: []
        # livenessProbe:
        #   # failureThreshold: 3
        #   # periodSeconds: 10
        #   # successThreshold: 1
        #   # timeoutSeconds: 1
        #   httpGet:
        #     path: /
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        resources:
          requests:
            cpu: 5m
            memory: 64Mi
          limits: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/cof.g
      securityContext: {}
      volumes:
      - name: conf
        emptyDir: {}
      - name: tmpdir
        emptyDir: {}

---
kind: Service
apiVersion: v1
metadata:
  name: external-http
spec:
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: external-http
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 32080
    targetPort: 80
  - name: https
    port: 443
    nodePort: 32443
    targetPort: 443
  - name: ui
    port: 8080
    nodePort: 32081
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-http
  # annotations:
  #   cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare-dns
spec:
  # tls:
  # - hosts:
  #   - prod-console.buc.sh
  #   secretName: cert-evergreen-console-buc-sh
  rules:
  - host: external-http.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-http
            port:
              number: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: okd-console-http
spec:
  rules:
  - host: prod.10.0.0.21.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: okd-console
            port:
              number: 9000
