kind: Kustomization

namespace: sqlite-backup


helmCharts:
- name: redis
  # repo: https://charts.bitnami.com/bitnami
  repo: oci://registry-1.docker.io/bitnamicharts/
  releaseName: redis-ephemeral
  version: 22.0.6
  namespace: sqlite-backup
  includeCRDs: true
  valuesInline:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: false

resources:
- s3.yaml
- syncthing-test.yaml
- paperless-test.yaml
- s3-test.yaml