apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd-deploy
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  targetNamespace: argocd
  valuesContent: |-
    global:
      logging:
        format: text
      networkPolicy:
        create: true
    redis:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    redis-ha:
      enabled: false
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      enableStatefulSet: false
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    applicationSet:
      replicas: 1
      metrics:
        enabled: true
        seviceMonitor:
          enabled: false
    server:
      replicas: 1
      extraArgs:
        - --insecure
      ingress:
        enabled: true
        hosts:
        - argocd.10.0.0.33.nip.io
        - argocd.buc.sh
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
      config:
        admin.enabled: "true"
        resource.compareoptions: |
          ignoreAggregatedRoles: true
        configManagementPlugins: |
          - name: kustomized-helm
            generate:
              command: [sh, -c]
              args: ["kustomize build --enable-helm"]
    repoServer:
      replicas: 1
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          cpu: 250m
          memory: 500Mi
    dex:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 128Mi
    configs:
      secret:
        createSecret: true
        # extra:
        #   accounts.socradev.password: $2a$10$FGEET8BeGazPQvwADx4rZuIt2MKNrtLpomNHTtaFBp.EjdfDxuWGy


