---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  labels:
    app.kubernetes.io/name: element
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: element
  template:
    metadata:
      labels:
        app.kubernetes.io/name: element
    spec:
      containers:
      - name: element
        image: ghcr.io/element-hq/element-web:v1.12.2
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /config.json
            port: http
        readinessProbe:
          httpGet:
            path: /config.json
            port: http
        resources:
          requests:
            cpu: 5m
            memory: 100Mi
          limits: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /usr/share/nginx/html/config.chat.10.0.0.21.nip.io.json
          name: config
        - mountPath: /usr/share/nginx/html/config.chat.cloud.buc.sh.json
          name: config
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      volumes:
      - name: config
        configMap:
          name: element-config
          items:
          - key: element-config.json
            path: config.chat.10.0.0.21.nip.io.json
          - key: element-config.json
            path: config.chat.cloud.buc.sh.json
---
kind: Service
apiVersion: v1
metadata:
  name: element
spec:
  selector:
    app.kubernetes.io/name: element
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
