
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: matrix-cloud-buc-sh
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external-gateway
    namespace: external-gateway
  hostnames:
  - "matrix.cloud.buc.sh"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: synapse
      port: 8008
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /_matrix
    - path:
        type: PathPrefix
        value: /_synapse/client
    - method: GET
      path:
        type: PathPrefix
        value: /.well-known

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: chat-cloud-buc-sh
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: external-gateway
    namespace: external-gateway
  hostnames:
  - "chat.cloud.buc.sh"
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: element
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: spdf
# spec:
#   podSelector:
#     matchLabels:
#       app.kubernetes.io/name: synapse
#   policyTypes:
#     - Ingress
#     - Egress
#   ingress:
#   # Allow Ingress
#   - from:
#     - namespaceSelector:
#         matchLabels:
#           kubernetes.io/metadata.name: traefik
#     ports:
#     - protocol: TCP
#       port: 8008
