apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-database
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: "local-path"
  bootstrap:
    initdb:
      database: matrix
      owner: matrix

      # dataChecksums: true
      # localeCollate: 'en_US'
      # localeCType: 'en_US'
      # postInitSQL:
      #   - CREATE DATABASE angus