apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-database
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: "local-path"
  bootstrap:
    initdb:
      database: matrix
      owner: matrix

      # dataChecksums: true
      localeCollate: 'de_AT'
      localeCType: 'de_AT'
      postInitSQL:
      - CREATE DATABASE matrix_mas WITH owner=matrix;