---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  labels:
    app.kubernetes.io/name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: synapse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synapse
    spec:
      containers:
      - name: synapse
        image: ghcr.io/element-hq/synapse:v1.140.0
        ports:
        - name: http
          containerPort: 8008
        volumeMounts:
        - name: configs
          mountPath: /data
        - name: db
          mountPath: /db
        - name: media
          mountPath: /media
        - name: tmp
          mountPath: /tmp/
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /health
            port: 8008
        readinessProbe:
          httpGet:
            path: /health
            port: 8008
        resources:
          requests:
            cpu: 5m
            memory: 100Mi
          limits: {}
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      volumes:
      - name: configs
        configMap:
          name: synapse-data
      - name: db
        emptyDir: {}
      - name: media
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: synapse
spec:
  selector:
    app.kubernetes.io/name: synapse
  type: ClusterIP
  ports:
    - name: http
      port: 8008
      targetPort: 8008

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse
spec:
  rules:
  - host: chat.cloud.buc.sh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synapse
            port:
              number: 8008
  - host: chat.10.0.0.21.nip.io
    http:
      paths:
      - path: /_matrix
        pathType: Prefix
        backend:
          service:
            name: synapse
            port:
              number: 8008
      - path: /.well-known
        pathType: Prefix
        backend:
          service:
            name: synapse
            port:
              number: 8008
      - path: /
        pathType: Prefix
        backend:
          service:
            name: element
            port:
              number: 80

