namespace: traefik

helmCharts:
- name: traefik-crds
  releaseName: traefik-crds
  repo: https://traefik.github.io/charts
  version: 1.18.0
- name: traefik
  releaseName: traefik
  namespace: traefik
  includeCRDs: false
  repo: https://traefik.github.io/charts
  version: 41.0.1
  valuesFile: values.yaml

resources:
- ns.yaml