---
apiVersion: v1
kind: Namespace
metadata:
  name: immich

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-cert
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: k8s-evergreen
    kind: ClusterSecretStore
  target:
    name: cert-immich-buc-sh
    creationPolicy: Owner
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: cert-immich-buc-sh

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-tls
  namespace: immich
spec:
  tls:
  - hosts:
      - immich.buc.sh
    secretName: cert-immich-buc-sh
  rules:
  - host: "immich.buc.sh"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: immich-server
            port:
              name: http

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "local-path"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-library-nfs
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: ""
#   volumeName: immich-library

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: immich-library
# spec:
#   capacity:
#     storage: 4Ti
#   accessModes:
#   - ReadWriteMany
#   - ReadOnlyMany
#   nfs:
#     server: 10.0.0.19
#     path: /mnt/user/data/kubernetes/immich
#   mountOptions:
#   - nfsvers=4.2
#   - retrans=3
#   - ac         # Fileattribute cache
#   - fsc        # File cache
#   # # if NFS server is unreachable, block all IO
#   - hard
#   - timeo=600
