---
apiVersion: v1
kind: Namespace
metadata:
  name: immich


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
spec:
  - host: immich.10.0.0.21.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-server
            port:
              name: http


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "local-path"

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: immich-library
# spec:
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: ""
#   volumeName: immich-library

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: immich-library
# spec:
#   capacity:
#     storage: 4Ti
#   accessModes:
#   - ReadWriteMany
#   - ReadOnlyMany
#   nfs:
#     server: 10.0.0.19
#     path: /mnt/user/data/kubernetes/paperlessngx
#   mountOptions:
#   - nfsvers=4.2
#   - retrans=3
#   - ac         # Fileattribute cache
#   - fsc        # File cache
#   # # if NFS server is unreachable, block all IO
#   - hard
#   - timeo=600
