---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd
spec:
  rules:
  - host: "argocd.10.0.0.21.nip.io"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argocd-server
            port:
              number: 80
