
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "true"
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
  resource.compareoptions: |
    ignoreAggregatedRoles: true
  resource.customizations: |
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs
  # Build options/parameters to use with `kustomize build` (optional)
  kustomize.buildOptions: --enable-helm
  # # OIDC configuration as an alternative to dex (optional).
  # oidc.config: |
  #   name: Vault
  #   issuer: https://vault.buc.sh/v1/identity/oidc/provider/global
  #   clientID: Fkc7DuB6FK3nDTAzshJZ9sOeXtyVZ0rj
  #   clientSecret: $oidc.client_secret
  #   # # Optional set of OIDC scopes to request. If omitted, defaults to: ["openid", "profile", "email", "groups"]
  #   # requestedScopes: ["openid", "profile", "email"]
  #   # # Optional set of OIDC claims to request on the ID token.
  #   # requestedIDTokenClaims: {"groups": {"essential": true}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # # Open-Telemetry collector address: (e.g. "otel-collector:4317")
  # otlp.address:
  
  # Run server without TLS
  server.insecure: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
stringData:
  admin.password: $2a$10$C8QN1YJaoW/.L6bBSV/k1ucgA5Wm68JkyHPyyT8/Lke.UjwAaf73y
