apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  targetNamespace: argocd
  valuesContent: |-
    controller:
      enableStatefulSet: false
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
      config:
        admin.enabled: "true"
        resource.compareoptions: |
          ignoreAggregatedRoles: true
        configManagementPlugins: |
          - name: kustomized-helm
            generate:
              command: [sh, -c]
              args: ["kustomize build --enable-helm"]
    dex:
    configs:
      secret:
        createSecret: true
        argocdServerAdminPassword: $2a$10$C8QN1YJaoW/.L6bBSV/k1ucgA5Wm68JkyHPyyT8/Lke.UjwAaf73y
