namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- additional_resources.yaml
- bootstrap.yaml

patchesStrategicMerge:
- argocd-config.yaml
