---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-s3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: paperless-s3-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-s3-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: ""
  mountOptions:
  - endpoint-url http://10.0.0.19:9000
  - region us-east-1
  - incremental-upload
  - upload-checksums crc32c
  - allow-delete
  - allow-overwrite
  - allow-other
  # - debug
  # - prefix path/in/bucket
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume    # Must be unique
    volumeAttributes:
      bucketName: paperless               # Configure BucketName
      # cache: emptyDir
      # cacheEmptyDirSizeLimit: 1Gi
      # cacheEmptyDirMedium: Memory
