secretGenerator:
- name: sealed-secrets-private-key
  namespace: kube-system
  files:
  - tls.crt=sealed.crt
  - tls.key=sealed.key
  type: kubernetes.io/tls
generatorOptions:
  DisableNameSuffixHash: true
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active