apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm
  namespace: paperless
spec:
  source:
    chart: redis
    repoURL:  oci://registry-1.docker.io/bitnamicharts/redis
    targetRevision: HEAD
    helm:
      releaseName: redis-ephemeral
      valuesContent: |-
        architecture: standalone
        auth:
          enabled: false
        master:
          persistence:
            enabled: false
  destination:
    server: "https://kubernetes.default.svc"