apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - list:
      elements:
      - name: external-secrets
        rev: talos
        path: gitops/external-secrets/base
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/thomasbuchinger/prod-gitops
        targetRevision: '{{rev}}'
        path: '{{path}}'
        plugin:
          name: kustomized-helm
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
