apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - list:
      elements:
      - name: external-secrets
        rev: main
        path: gitops/external-secrets/base
        wave: "1"
      - name: argocd
        rev: main
        path: gitops/argocd/additional_config
        wave: "2"
      - name: local-path-storage
        rev: main
        path: gitops/local-path-storage/base
        wave: "1"
      - name: okd-console
        rev: main
        path: gitops/okd-console
        wave: "1"
      - name: monitoring
        rev: prometheus
        path: gitops/monitoring/all
        wave: "1"
      - name: monitoring-loki
        rev: prometheus
        path: gitops/monitoring-loki
        wave: "1"
      - name: paperless
        rev: main
        path: gitops/paperless
        wave: "2"
      - name: syncthing
        rev: main
        path: gitops/syncthing
        wave: "2"
      - name: spdf
        rev: main
        path: gitops/stirling-pdf
        wave: "2"
      - name: external-http
        rev: prometheus
        path: gitops/external-http
        wave: "2"
      - name: external-homelabapi
        rev: prometheus
        path: gitops/external-homelabapi
        wave: "2"
      - name: external-r2
        rev: prometheus
        path: gitops/external-r2
        wave: "2"
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/thomasbuchinger/prod-gitops
        targetRevision: '{{rev}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
