apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - list:
      elements:
      # == Cluster Infra ===
      - name: external-secrets
        path: gitops/external-secrets/base
        wave: "1"
      - name: argocd
        path: gitops/argocd/additional_config
        wave: "2"
      - name: local-path-storage
        path: gitops/local-path-storage/base
        wave: "1"
      - name: csi-mountpoint-s3
        path: gitops/csi-mountpoint-s3
        wave: "2"
      - name: okd-console
        path: gitops/okd-console
        wave: "1"
      - name: monitoring-prometheus
        path: gitops/monitoring/prometheus
        wave: "1"
      - name: monitoring-loki
        path: gitops/monitoring/loki
        wave: "2"
      - name: monitoring-tempo
        path: gitops/monitoring/tempo
        wave: "2"
      - name: monitoring-shared
        path: gitops/monitoring/shared
        wave: "2"
      # === Apps ===
      - name: paperless
        path: gitops/paperless
        wave: "2"
      - name: syncthing
        path: gitops/syncthing
        wave: "2"
      - name: spdf
        path: gitops/stirling-pdf
        wave: "1"
      - name: matrix
        path: gitops/matrix
        wave: "1"
      - name: mediarr
        path: gitops/mediarr
        wave: "1"
      - name: s3manager
        path: gitops/s3manager
        wave: "1"
      - name: netalertx
        path: gitops/netalertx
        wave: "1"
      # === Internet Facing
      - name: external-gateway
        path: gitops/external-gateway
        wave: "2"
      - name: external-homelabapi
        path: gitops/external-homelabapi
        wave: "2"
      - name: external-hfs
        path: gitops/external-hfs
        wave: "2"
      - name: external-frigate
        path: gitops/external-frigate
        wave: "2"
      - name: external-homeassistant
        path: gitops/external-homeassistant
        wave: "2"
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/thomasbuchinger/prod-gitops
        targetRevision: feat-netalertx
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - ServerSideApply=true
        - CreateNamespace=true
