apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-wide
spec:
  generators:
  - list:
      elements: []
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{wave}}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/thomasbuchinger/prod-gitops
        targetRevision: '{{rev}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}
        syncOptions:
        - ServerSideApply=true
